apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: roarapps.app.example.com
spec:
  group: app.example.com
  names:
    kind: RoarApp
    listKind: RoarAppList
    plural: roarapps
    singular: roarapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            replicas:
              format: int32
              type: integer
          required:
          - replicas
          type: object
        status:
          properties:
            podNames:
              items:
                type: string
              type: array
          required:
          - podNames
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
